name: riskified
description: Flutter plugin for Riskified SDK
version: 0.0.1
homepage: https://github.com/appunite/flutter_riskified

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.riskified
        pluginClass: RiskifiedPlugin
      ios:
        pluginClass: RiskifiedPlugin